- hosts: ios

  tasks:
  - name: make interface up 5GHz
    ios_interface:
      name: Dot11Radio1
      enabled: True
    when:
    - has_5g_radio|bool
    tags:
    - 80211a

  - name: make interface up 2.4GHz
    ios_interface:
      name: Dot11Radio0
      enabled: True
    tags:
    - 80211b

  - name: save running to startup when modified
    ios_config:
      save_when: modified
    # Save system config with default radios enabled.
    # This is to mitigate against an unintended system state save after radios were shut down
