- hosts: ios

  tasks:
# - name: kill radio - 2.4
#   ios_config:
#     lines:
#     - shutdown
#     parents: 
#     - interface Dot11Radio 0
#     - interface Dot11Radio 1

  - name: make interface up 5GHz
    ios_interface:
      name: Dot11Radio1
      enabled: True
    when:
    - has_5g_radio
    tags:
    - 80211a

  - name: make interface up 2.4GHz
    ios_interface:
      name: Dot11Radio0
      enabled: True
    tags:
    - 80211b

  - name: save running to startup when modified
    ios_config:
      save_when: modified
