  # prerequisite: enable sshd service on AP

- hosts: ap
  gather_facts: no
  connection: network_cli
  become_method: enable

  vars:
    ansible_user: cisco
    ansible_password: Cisco
    ansible_become_password: Cisco

  handlers:
  - name: save configuration
    ios_config:
      save_when: modified

  roles:
  - ansible-filter-cisco-hash

  tasks:
  - name: create the ansible user
    ios_user:
      name: ansible
      hashed_password:
        type: 5
        value: "{{ansible_password_a | ciscohash5( 9 | random(seed=inventory_hostname) | string )}}"
        #value: "{{ansible_password_a | password_hash('md5', 9 | random(seed=inventory_hostname) | string )}}"
        #  {{ 'secretpassword' | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}
      password_type: secret
      privilege: 15
      sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      state: present
    notify: save configuration



  - name: set hostname and update enable password
    ios_config:
      lines:
      - hostname {{ inventory_hostname }}
      - enable secret 5 {{ ansible_become_password_a| password_hash('md5', 9 | random(seed=inventory_hostname) | string ) }}
    notify: save configuration

  - name: update the cisco user
    ios_user:
      name: cisco
      hashed_password:
        type: 5
        value: "{{ansible_password_a | ciscohash5( 9 | random(seed=inventory_hostname) | string )}}"
        #value: "{{ansible_password_a | password_hash('md5', 9 | random(seed=inventory_hostname) | string )}}"
        #  {{ 'secretpassword' | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}
      password_type: secret
      state: present
    notify: save configuration
