  # prerequisite: enable sshd service on AP
  # for followup run (after some access parameters have already been modified):
  #   playbooks/ap/set-access.yml -e followup_run_bs=true

- hosts: ap
  gather_facts: no
  connection: network_cli
  become_method: enable

  handlers:
  - name: save configuration
    ios_config:
      save_when: modified

  roles:
  - ansible-filter-cisco-hash

  tasks:
  - include_vars: bootstrap-vars.yml
    when: not followup_run_bs

  - name: assert all variables needed are set
    assert:
      that: "{{ item }} is defined"
      fail_msg: "some missing variables need defining"
      quiet: yes
    with_items:
        - ansible_password_a
        - ansible_become_password_a
        - ansible_user
        - ansible_password
        - ansible_become_password
        - ansible_become_method

  - name: create the ansible user
    ios_user:
      name: ansible
      hashed_password:
        type: 5
        value: "{{ansible_password_a | ciscohash5( 9 | random(seed=inventory_hostname) | string )}}"
        #value: "{{ansible_password_a | password_hash('md5', 9 | random(seed=inventory_hostname) | string )}}"
        #  {{ 'secretpassword' | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}
      password_type: secret
      privilege: 15
      sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      state: present
    notify: save configuration

  - name: set hostname, update enable password, deconfigure telnet
    ios_config:
      lines:
      - hostname {{ inventory_hostname }}
      - enable secret 5 {{ ansible_become_password_a| password_hash('md5', 9 | random(seed=inventory_hostname) | string ) }}
      - no access-list 111
    notify: save configuration

  - name: update cisco user access
    ios_user:
      name: cisco
      hashed_password:
        type: 5
        value: "{{ansible_password_a | ciscohash5( 9 | random(seed=inventory_hostname) | string )}}"
        #value: "{{ansible_password_a | password_hash('md5', 9 | random(seed=inventory_hostname) | string )}}"
        #  {{ 'secretpassword' | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}
      password_type: secret
      state: present
    notify: save configuration
